---
- hosts: all
  gather_facts: False
  # Thanks https://github.com/ansible/ansible/issues/14199
  become_user: root
  become: True
  roles:
    - bootstrap_python

- hosts: all
  # Thanks https://github.com/ansible/ansible/issues/14199
  become_user: root
  become: True
  roles:
    - base
    - docker
    - remove_authorized_keys
