---
- name: "Remove default motd scripts"
  file:
    path:   "/etc/update-motd.d/{{ item }}"
    state:  "absent"
  with_items:
    - 00-header
    - 10-help-text
    - 51-cloudguest
    - 90-updates-available
    - 91-release-upgrade
    - 97-overlayroot
    - 98-fsck-at-reboot
    - 98-reboot-required

- name: "Configure main MOTD"
  template:
    src:    motd.sh
    dest:   /etc/update-motd.d/00-motd
    owner:  root
    group:  root
    mode:   0755
